version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  redis:
    driver: ${VOLUMES_DRIVER}

services:

### Workspace Utilities ##################################
    workspace:
      image: aidong-backend.tencentcloudcr.com/aidong/php-workspace:1.0.0
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./php-worker/supervisord.d:/etc/supervisord.d
        - ./php-worker/supervisord.conf:/etc/supervisord.conf
        - ./workspace/yaconf:/usr/local/etc/yaconf

      extra_hosts:
        - "homestead.linde:172.20.0.1"
        - "homestead.linde.fastapi:172.20.0.1"
        - "homestead.hbsd:172.20.0.1"
        - "homestead.watch:172.20.0.1"
        - "homestead.watch.fastapi:172.20.0.1"
        - "homestead.linde.cms:172.20.0.1"
        - "homestead.td:172.20.0.1"
      ports:
        - "25080:25080"
        - "25081:25081"
      tty: true
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        - frontend
        - backend

### PHP-FPM ##############################################
    php-fpm:
      image: aidong-backend.tencentcloudcr.com/aidong/php-fpm:1.0.0
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      expose:
        - "9000"
      extra_hosts:
        - "homestead.linde:172.20.0.1"
        - "homestead.linde.fastapi:172.20.0.1"
        - "homestead.hbsd:172.20.0.1"
        - "homestead.watch:172.20.0.1"
        - "homestead.watch.fastapi:172.20.0.1"
        - "homestead.linde.cms:172.20.0.1"
        - "homestead.td:172.20.0.1"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - FAKETIME=${PHP_FPM_FAKETIME}
      depends_on:
        - workspace
      networks:
        - backend

### PHP Worker ############################################
    php-worker:
      image: aidong-backend.tencentcloudcr.com/aidong/php-worker:1.0.0
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./php-worker/supervisord.d:/etc/supervisord.d
        - ./php-worker/supervisord.conf:/etc/supervisord.conf
      depends_on:
        - workspace
      extra_hosts:
        - "homestead.linde:172.20.0.1"
        - "homestead.linde.fastapi:172.20.0.1"
        - "homestead.hbsd:172.20.0.1"
        - "homestead.watch:172.20.0.1"
        - "homestead.watch.fastapi:172.20.0.1"
        - "homestead.linde.cms:172.20.0.1"
        - "homestead.td:172.20.0.1"
      networks:
        - backend

### NGINX Server #########################################
    nginx:
      image: aidong-backend.tencentcloudcr.com/aidong/php-nginx:1.0.0
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### Redis ################################################
    redis:
      image: redis:latest
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - backend

